# Generated by Django 3.1.2 on 2022-05-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220507_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/deafult-profile-image.png', null=True, upload_to='images/profile/'),
        ),
    ]
